description: |-
  Copyright 2023 <GATech EPL>
  Author: Jordan Rapp <jrapp7@gatech.edu>
  Content: This is the scenario testing configuration file for platooning joining and cooperative merge
           at the Town06 using  CARLA only.

# eCloudSim
distributed: true  # set to false or comment out to run "standard" OpenCDA sequential sims
define: &perception_is_active false
perception_active: *perception_is_active

# define carla simulation setting
world:
  # spectate settings
  x_pos: 256
  z_pos: 512
  roll: 90
  sync_mode: true
  client_port: 2000
  fixed_delta_seconds: &delta 0.05
  seed: 87
  weather:
    sun_altitude_angle: 15 # 90 is the midday and -90 is the midnight
    cloudiness: 0 # 0 is the clean sky and 100 is the thickest cloud
    precipitation: 0 # rain, 100 is the heaviest rain
    precipitation_deposits: 0 # Determines the creation of puddles. Values range from 0 to 100, being 0 none at all and 100 a road completely capped with water.
    wind_intensity: 0 # it will influence the rain
    fog_density: 0 # fog thickness, 100 is the largest
    fog_distance: 0  # Fog start distance. Values range from 0 to infinite.
    fog_falloff: 0 # Density of the fog (as in specific mass) from 0 to infinity. The bigger the value, the more dense and heavy it will be, and the fog will reach smaller heights
    wetness: 0

ecloud:
  log_level: 10 # DEBUG - uses logging.LEVEL enums

# First define the basic parameters of the vehicles
vehicle_base: &vehicle_base
  sensing: &base_sensing
    perception: &base_perception
      activate: false # when not activated, objects positions will be retrieved from server directly
      camera_visualize: 0 # how many camera images need to be visualized. 0 means no visualization for camera
      camera_num: 1 # how many cameras are mounted on the vehicle. Maximum 3(frontal, left and right cameras)
      lidar_visualize: false # whether to visualize lidar points using open3d
      lidar: # lidar sensor configuration, check CARLA sensor reference for more details
        channels: 32
        range: 50
        points_per_second: 100000
        rotation_frequency: 20 # the simulation is 20 fps
        upper_fov: 15.0
        lower_fov: -30.0
        dropoff_general_rate: 0.0
        dropoff_intensity_limit: 1.0
        dropoff_zero_intensity: 0.0
        noise_stddev: 0.0
    localization: &base_localize
      activate: true # when not activated, ego position will be retrieved from server directly
      dt: *delta # used for kalman filter
      gnss: # gnss sensor configuration
        noise_alt_stddev: 0.001
        noise_lat_stddev: 1.0e-6
        noise_lon_stddev: 1.0e-6
        heading_direction_stddev: 0.1 # degree
        speed_stddev: 0.2
      debug_helper: &loc_debug_helper
        show_animation: false # whether to show real-time trajectory plotting
        x_scale: 1.0 # used to multiply with the x coordinate to make the error on x axis clearer
        y_scale: 100.0 # used to multiply with the y coordinate to make the error on y axis clearer
  behavior: &base_behavior
    max_speed: 70 # maximum speed, km/h
    tailgate_speed: 80 # when a vehicles needs to be close to another vehicle asap
    speed_lim_dist: 3 # max_speed - speed_lim_dist = target speed
    speed_decrease: 15 # used in car following mode to decrease speed for distance keeping
    safety_time: 4 # ttc safety thresholding for decreasing speed
    emergency_param: 0.4 # used to identify whether a emergency stop needed
    ignore_traffic_light: true # whether to ignore traffic light
    overtake_allowed: false # whether overtake allowed, typically false for platoon leader
    collision_time_ahead: 1.1 # used for collision checking
    overtake_counter_recover: 35 # the vehicle can not do another overtake during next certain steps
    sample_resolution: 4.5 # the unit distance between two adjacent waypoints in meter
    local_planner: &base_local_planner # trajectory planning related
      buffer_size: 12 # waypoint buffer size
      trajectory_update_freq: 15 # used to control trajectory points updating frequency
      waypoint_update_freq: 9 # used to control waypoint updating frequency
      min_dist: 3 # used to pop out the waypoints too close to current location
      trajectory_dt: 0.20 # for every dt seconds, we sample a trajectory point from the trajectory path as next goal state
      debug: false # whether to draw future/history waypoints
      debug_trajectory: false # whether to draw the trajectory points and path
  controller: &base_controller
    type: pid_controller # this has to be exactly the same name as the controller py file
    args: &control_args
      lat:
        k_p: 0.75
        k_d: 0.02
        k_i: 0.4
      lon:
        k_p: 0.37
        k_d: 0.024
        k_i: 0.032
      dynamic: false # whether use dynamic pid setting
      dt: *delta # this should be equal to your simulation time-step
      max_brake: 1.0
      max_throttle: 1.0
      max_steering: 0.3
  v2x: &base_v2x # comminuation related
    enabled: true
    communication_range: 35
    loc_noise: 0.0
    yaw_noise: 0.0
    speed_noise: 0.0
    lag: 0

# define the background traffic control by carla
carla_traffic_manager:
  sync_mode: true # has to be same as the world setting
  global_distance: 4.0 # the minimum distance in meters that vehicles have to keep with the rest
  # Sets the difference the vehicle's intended speed and its current speed limit.
  #  Carla default speed is 30 km/h, so -100 represents 60 km/h,
  # and 20 represents 24 km/h
  global_speed_perc: -50
  set_osm_mode: true # Enables or disables the OSM mode.
  auto_lane_change: false
  random: false # whether to random select vehicles' color and model
  ignore_lights_percentage: 0 # whether set the traffic ignore traffic lights
  vehicle_list:
  range: []

# define scenario. In this scenario, a 4-vehicle platoon already exists.
scenario:
  ecloud: 
    num_cars: 4
    location_type: random # random || explicit - applies to spawn & destination
    done_behavior: control # destroy || control - stop || drive - new destination
  single_cav_list: # this is for merging vehicle or single cav without v2x
    - <<: *vehicle_base
      sensing:
        <<: *base_sensing
        perception:
          <<: *base_perception
          activate: false
          camera_visualize: 0
          camera_num: 3
          lidar_visualize: false
        localization:
          <<: *base_localize
          debug_helper:
            <<: *loc_debug_helper
            show_animation: false
      v2x:
        <<: *base_v2x
        communication_range: 35
      behavior:
        <<: *base_behavior
        max_speed: 100 # maximum speed, km/h
        tailgate_speed: 111
        overtake_allowed: true
        local_planner:
          <<: *base_local_planner
          debug_trajectory: true
          debug: true
